jobs: 100
reason: True
use-conda: True
latency-wait: 60
printshellcmds: True
show-failed-logs: True
rerun-incomplete: True
cluster-cancel: "scancel"
cluster: "sbatch -p {resources.queue} -t {resources.time} --mem={resources.mem_mb} -c {resources.cpus} -o {log.cluster_log} -e {log.cluster_err}"
