executor: cluster-generic
cluster-generic-submit-cmd: sbatch
    --partition={resources.slurm_partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.runtime}
    --job-name=smk-{rule}-{wildcards}
    --output={log.cluster_log}
    --error={log.cluster_err}
    --parsable # Required to pass job IDs to scancel
scheduler: greedy
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
use-conda: True

jobs: 100
printshellcmds: True
rerun-incomplete: True
latency-wait: 60
cluster-generic-cancel-cmd: scancel
cluster-generic-cancel-nargs: 50
