executor: slurm
jobs: 100
use-conda: True
latency-wait: 60
printshellcmds: True
show-failed-logs: True
rerun-incomplete: True

default-resources:
    slurm_partition: "main"
    runtime: 60
    mem_mb: 2000
    cpus_per_task: 1
